backend:
  name: github
  repo: MickaKymm95/portfolio
  branch: main
  squash_merges: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://kymmphotography.netlify.app/"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: src/content/portfolio
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "publishedAt", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Photo", name: "heroImage", widget: "image", required: false }
      - { label: "Catégorie", name: "category", widget: "select", options: ["Portrait", "Paysage", "Mariage", "Événement", "Autre"], required: false }
      - { label: "Publier", name: "isPublish", widget: "boolean", default: true }
      - { label: "Contenu", name: "body", widget: "markdown" }
